# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Pranaydeep Singh
tagline:          'c1pher'
description:      'Postdoctoral Researcher at LT3 & T2K, Ghent University'
url:              https://pranaydeep.xyz
baseurl:          /

author:
  name:           'Pranaydeep Singh'
  email:          'pranaydeep.singh@ugent.be'
  url:            https://github.com/pranaydeeps

paginate:         5
paginate_path: "Blog/page:num/"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/pranaydeeps

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
